import React from 'react';
import { ArrowUpRight, Bell, CircleDollarSign, Clock3, Package, ShoppingBag, Star } from 'lucide-react';

export default function Overview() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-1"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-pink">Good morning, seller</p><h2 className="font-display text-3xl font-extrabold text-brand-teal">Your store at a glance</h2><p className="text-sm text-gray-500">Here is what needs your attention today.</p></div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {[['Revenue this month', '₹1,84,620', '+13.7%', CircleDollarSign, 'text-brand-blue', 'bg-brand-blue-subtle'], ['Orders this month', '284', '+14.1%', ShoppingBag, 'text-brand-green', 'bg-brand-green-subtle'], ['Active products', '126', '+8 this month', Package, 'text-brand-pink', 'bg-brand-pink-subtle'], ['Store rating', '4.8 / 5', '+0.2 this month', Star, 'text-brand-ochre', 'bg-brand-yellow-light']].map(([label, value, change, Icon, color, surface]) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className={`rounded-lg p-2.5 ${surface}`}><Icon className={color} size={20} /></div><ArrowUpRight className="text-brand-green" size={17} /></div><p className="mt-4 text-xs font-bold uppercase tracking-wide text-gray-400">{label}</p><p className="mt-1 font-display text-2xl font-extrabold text-brand-teal">{value}</p><p className="mt-1 text-xs font-semibold text-brand-green">{change}</p></div>)}
      </div>
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1.35fr_1fr]">
        <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-bold text-brand-teal">Revenue performance</h3><p className="text-xs text-gray-400">Last 7 days</p></div><span className="rounded-full bg-brand-green-subtle px-2.5 py-1 text-xs font-bold text-brand-green">+13.7%</span></div><div className="mt-6 flex h-44 items-end gap-2 sm:gap-4">{[['Mon', 42], ['Tue', 58], ['Wed', 48], ['Thu', 72], ['Fri', 64], ['Sat', 88], ['Sun', 76]].map(([day, height]) => <div key={day} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-36 w-full items-end"><div className="w-full rounded-t-md bg-brand-teal transition hover:bg-brand-yellow" style={{ height: `${height}%` }} /></div><span className="text-[11px] font-semibold text-gray-400">{day}</span></div>)}</div></div>
        <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold text-brand-teal">Needs attention</h3><Bell className="text-brand-pink" size={18} /></div><div className="mt-4 space-y-3">{[['3', 'Orders waiting for confirmation', ShoppingBag], ['2', 'Products are low on stock', Package], ['1', 'School quotation due this week', Clock3]].map(([count, label, Icon]) => <div key={label} className="flex items-center gap-3 rounded-lg bg-gray-50 p-3"><div className="rounded-full bg-brand-yellow px-2 py-1 text-xs font-extrabold text-brand-teal">{count}</div><Icon size={16} className="text-brand-teal" /><span className="text-sm font-semibold text-gray-600">{label}</span></div>)}</div></div>
      </div>
      <div className="rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-100 p-5"><div><h3 className="font-display text-lg font-bold text-brand-teal">Recent activity</h3><p className="text-xs text-gray-400">Your latest store updates</p></div><button className="text-xs font-bold text-brand-pink hover:underline">View all</button></div><div className="divide-y divide-gray-100">{[['New order #BV-1048 received', 'Aarav Sharma placed an order worth ₹1,249', '10 min ago', ShoppingBag], ['Review received for Camlin Exam Kit', 'Meera Iyer rated your product 5 stars', '1 hour ago', Star], ['Payout scheduled', '₹1,66,158 will be deposited on 17 Jun', 'Yesterday', CircleDollarSign]].map(([title, detail, time, Icon]) => <div key={title} className="flex items-center gap-3 p-5"><div className="rounded-lg bg-brand-teal-subtle p-2.5"><Icon className="text-brand-teal" size={17} /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-gray-700">{title}</p><p className="truncate text-xs text-gray-500">{detail}</p></div><span className="text-xs text-gray-400">{time}</span></div>)}</div></div>
    </div>
  );
}
